### ISSUE TITLE
TOC breaks when section numbers disabled in org-mode 8.3.x

### ISSUE THREAD

**Issue by marsmining** [marsmining/ox-twbs#10]
With Org 8.2.x `:section-number nil` just toggled the display of section numbers, but the "id" attribute was in place. Org-mode 8.3.x parsing of the document will not include headline numbering if `:section-number nil`, therefore section numbers are broken at the actual section and the TOC meant to link there.

**Comment by avivo** [comment]
As a temporary workaround, I've added this css to the export styles. It seems to work for me!

```
span[class^="section-number-"] { display: none; }
```

**Comment by marsmining** [comment]
Thanks for the help! I briefly considered your CSS solution, and opted for a solution which omits the HTML. Perhaps hiding via CSS is better, but this seemed simpler right now.

I've added a new option, `:with-headline-numbers` for use in `org-publish-project-alist` or in the document via the acronym `#+OPTIONS: whn:nil`. It can be set to `nil` for no display, `t` for always display, or a number defining section numbers to display up to that number.

As a full example, the following:

```
#+OPTIONS: num:5 whn:2 toc:4 H:6
```

Would mean create section numbers up to level 5 (num). Display section numbers up to level 2 (whn). Display table of contents 4 deep (toc). Finally, consider sections after 6 to be "low-level" (H).

**Comment by kaushalmodi** [comment]
@marsmining That's a great example you put there. Can you put this into documentation when you get a chance. Thanks! This last update works great for me too on org-mode 8.3.x. For me the options are `whn:nil toc:3`.

**Comment by marsmining** [comment]
Thanks all. Closing this as it appears things are working ok.
