### ISSUE TITLE
Exported internal links display as numbers

### ISSUE THREAD

**Issue by avivo** [marsmining/ox-twbs#11]
With this input:

```
 * A
 [[A]]
```

The output is:

```
 <div id="outline-container-sec-1" class="outline-2">
    <h2 id="sec-1"><span class="section-number-2">1</span> A</h2>
    <div class="outline-text-2" id="text-1">
        <p>
        <a href="#sec-1">1</a>
        </p>
    </div>
</div>
```

Note that the link text in the output is unfortunately not "A" -- it's "1".

If I normally export HTML it works. This only happens in Org 8.3 (or perhaps with the latest version of twbs).
For now I am forced to revert to Org 8.2 to get things to work.

**Comment by marsmining** [comment]
Hi @avivo, sorry to take so long on this issue. I had a moment to look at this, and pushed a fix. It should be available on melpa in the next couple hours. If you're still in a position to test it, give it a shot, at your convenience.

The old logic would render description as number if section numbers were turned on. The new logic will always render internal links without a description with the destination's title.
