### ISSUE TITLE
"Unknown keyword: :export-block" when using the latest beta of org-mode

### ISSUE THREAD

**Issue by kaushalmodi** [marsmining/ox-twbs#13]
Hi,

I am on this org-mode version:

> Org-mode version 8.3.2 (release_8.3.2-457-g4a6d19 @ /home/kmodi/usr_local/apps/6/emacs/emacs-25/share/emacs/site-lisp/org/)

( http://orgmode.org/cgit.cgi/org-mode.git/commit/?id=4a6d195dea5edfff5badebdde5bc217ad5af0fdd )

With that, I am getting the below error when I evaluate ox-twbs,el:

``` el
Debugger entered--Lisp error: (error "Unknown keyword: :export-block")
  signal(error ("Unknown keyword: :export-block"))
  error("Unknown keyword: %s" :export-block)
  org-export-define-backend(twbs ((bold . org-twbs-bold) (center-block . org-twbs-center-block) (clock . org-twbs-clock) (code . org-twbs-code) (drawer . org-twbs-drawer) (dynamic-block . org-twbs-dynamic-block) (entity . org-twbs-entity) (example-block . org-twbs-example-block) (export-block . org-twbs-export-block) (export-snippet . org-twbs-export-snippet) (fixed-width . org-twbs-fixed-width) (footnote-definition . org-twbs-footnote-definition) (footnote-reference . org-twbs-footnote-reference) (headline . org-twbs-headline) (horizontal-rule . org-twbs-horizontal-rule) (inline-src-block . org-twbs-inline-src-block) (inlinetask . org-twbs-inlinetask) (inner-template . org-twbs-inner-template) (italic . org-twbs-italic) (item . org-twbs-item) (keyword . org-twbs-keyword) (latex-environment . org-twbs-latex-environment) (latex-fragment . org-twbs-latex-fragment) (line-break . org-twbs-line-break) (link . org-twbs-link) (paragraph . org-twbs-paragraph) (plain-list . org-twbs-plain-list) (plain-text . org-twbs-plain-text) (planning . org-twbs-planning) (property-drawer . org-twbs-property-drawer) (quote-block . org-twbs-quote-block) (quote-section . org-twbs-quote-section) (radio-target . org-twbs-radio-target) (section . org-twbs-section) (special-block . org-twbs-special-block) (src-block . org-twbs-src-block) (statistics-cookie . org-twbs-statistics-cookie) (strike-through . org-twbs-strike-through) (subscript . org-twbs-subscript) (superscript . org-twbs-superscript) (table . org-twbs-table) (table-cell . org-twbs-table-cell) (table-row . org-twbs-table-row) (target . org-twbs-target) (template . org-twbs-template) (timestamp . org-twbs-timestamp) (underline . org-twbs-underline) (verbatim . org-twbs-verbatim) (verse-block . org-twbs-verse-block)) :export-block "HTML" :filters-alist ((:filter-final-output . org-twbs-final-function)) :menu-entry (119 "Export to TWBS HTML" ((72 "As HTML buffer" org-twbs-export-as-html) (104 "As HTML file" org-twbs-export-to-html) (111 "As HTML file and open" (lambda (a s v b) (if a (org-twbs-export-to-html t s v b) (org-open-file (org-twbs-export-to-html nil s v b))))))) :options-alist ((:html-extension nil nil org-twbs-extension) (:html-link-org-as-html nil nil org-twbs-link-org-files-as-html) (:html-container "HTML_CONTAINER" nil org-twbs-container-element) (:html-link-use-abs-url nil "html-link-use-abs-url" org-twbs-link-use-abs-url) (:html-link-home "HTML_LINK_HOME" nil org-twbs-link-home) (:html-link-up "HTML_LINK_UP" nil org-twbs-link-up) (:html-mathjax "HTML_MATHJAX" nil "" space) (:html-postamble nil "html-postamble" org-twbs-postamble) (:html-preamble nil "html-preamble" org-twbs-preamble) (:html-head "HTML_HEAD" nil org-twbs-head newline) (:html-head-extra "HTML_HEAD_EXTRA" nil org-twbs-head-extra newline) (:html-head-include-default-style nil "html-style" org-twbs-head-include-default-style) (:html-head-include-scripts nil "html-scripts" org-twbs-head-include-scripts) (:html-table-attributes nil nil org-twbs-table-default-attributes) (:html-table-row-tags nil nil org-twbs-table-row-tags) (:html-inline-images nil nil org-twbs-inline-images) (:creator "CREATOR" nil org-twbs-creator-string) (:with-latex nil "tex" org-twbs-with-latex) (:with-toc nil nil 2) (:with-creator nil nil t) (:with-headline-numbers nil "whn" t) (:section-numbers nil nil t) (:latex-header "LATEX_HEADER" nil nil newline)))
```

I can avert the problem if I comment out this line: https://github.com/marsmining/ox-twbs/blob/cfe67353d148e65a7676f1609d8cc22a4c8fbc78/ox-twbs.el#L108

But I am not sure what's the right solution and so I have posted a question on the org-mode list: http://thread.gmane.org/gmane.emacs.orgmode/103736/focus=104051

**Comment by kaushalmodi** [comment]
Related hack to fix this on ox-reveal: https://github.com/yjwen/org-reveal/issues/185

**Comment by kaushalmodi** [comment]
Got [this update](http://thread.gmane.org/gmane.emacs.orgmode/103736/focus=104054) from Nicolas Goaziou

http://orgmode.org/cgit.cgi/org-mode.git/commit/?id=74c46ad0067ebf337f74ece4a86973c83adc7afa

**Comment by marsmining** [comment]
This is super helpful, thanks! To clarify, what version is this landing in? I see above you are saying v8.3.2 but I'm guessing you mean what will become v9 when you say "latest beta"? I found the [commit](http://orgmode.org/cgit.cgi/org-mode.git/commit/?id=54318add34f09ff39d3fd034a4c1a89f60fd8759) but not sure when it will be released.

**Comment by kaushalmodi** [comment]
I believe that this export block syntax change should already be in the
org-mode version 8.3.3 released 2 days back.

**Comment by marsmining** [comment]
I've tested v8.3.3 from elpa and all appears ok. I also downloaded v8.3.3 source from [this release tag](http://orgmode.org/cgit.cgi/org-mode.git/tag/?id=release_8.3.3) and it appears to me the changes are not there yet.

**Comment by kaushalmodi** [comment]
Hmm, in that case, I too don't know. I have asked that question on the same org-mode thread. Here's [the link](http://thread.gmane.org/gmane.emacs.orgmode/103736/focus=104109).

**Comment by kaushalmodi** [comment]
@marsmining You were correct. This syntax change will be effective in org-mode version 9.

**Comment by marsmining** [comment]
Thanks for everything! Next step perhaps is figuring out if removing the `:export-block "HTML"` argument in the `org-export-define-backend` function adversely effects org-mode v8. If so, we might need to detect which version user is using, and act accordingly.

**Comment by kaushalmodi** [comment]
Linking this issue to the master issue created to collect all changes required for org 9.x: https://github.com/marsmining/ox-twbs/issues/29

**Comment by marsmining** [comment]
Thanks @kaushalmodi for your help!
