### ISSUE TITLE
Style TODO states

### ISSUE THREAD

**Issue by tobsnk** [marsmining/ox-twbs#15]
The TODO states are currently just text. 
Bootstrap provides a "label" component which could be used to style the states to make them stand out more and make it look prettier.

In the same way you maybe could use the "badge" component for tags.

**Comment by marsmining** [comment]
Really great idea. I should have something to look at tomorrow for feedback.

**Comment by marsmining** [comment]
One month later! I pushed some commits which do as you suggest for todo keywords and tags. Take a look when you get some free time. To revert to old behavior you can customize these vars:

``` elisp
(setq org-twbs-tag-class "")
(setq org-twbs-todo-kwd-class-undone "todo")
(setq org-twbs-todo-kwd-class-done "done")
```

**Comment by tobsnk** [comment]
Yes, this is really fantastic. Thank you very much.

Would you happen to know how specify custom color or css class for the label depending on the name of the TODO state?
It would be cool to maybe have different colors for example a "NEXT" or "WAITING" or any other custom todo that I have. 
But I imagine this could be a bit too much work.
