### ISSUE TITLE
Wrong type argument: listp, "org-notes"

### ISSUE THREAD

**Issue by ReneFroger** [marsmining/ox-twbs#17]
Hi there!

Thanks for sharing this package! I decided to follow the tutorial on your readme.

Starting from `usage` section, I have the directories `org` and `public_html`
set up in my home directory.

I have the following setup:

```
(use-package ox-twbs
:config

(setq org-publish-project-alist
        '("org-notes"
        :base-directory "~/org/"
        :publishing-directory "~/public_html/"
        :publishing-function org-twbs-publish-to-html
        :with-sub-superscript nil
        ))
 )
```

When I call `org-publish-all` inside the org document, I got an error: 

```
org-publish-file: Wrong type argument: listp, "org-notes"
```

When googling around, it seems none have the same issue as I. So do  you have any suggestion how to tackle this issue?

**Comment by marsmining** [comment]
That is my mistake! Thanks very much for pointing it out.

The value of variable `org-publish-project-alist` should be a list of projects like:

``` elisp
(setq org-publish-project-alist
      '(("org-notes"
         :base-directory "~/org/"
         :publishing-directory "~/public_html/"
         :publishing-function org-twbs-publish-to-html
         :with-sub-superscript nil)))
```

**Comment by ReneFroger** [comment]
I decided to correct your readme. Could you update it?

**Comment by ReneFroger** [comment]
Nevermind, I see you updated it.
