### ISSUE TITLE
How to change the contents of the footer?

### ISSUE THREAD

**Issue by ReneFroger** [marsmining/ox-twbs#18]
Hi there! It's me again!

On the footer of the exported Org file to HTML, I see the following:

```
Author: Rene Froger
Created: 2016-01-23 za 20:35
Emacs 25.0.50.2 (Org mode 8.2.10)
```

I would like to change that. So I went to <kbd>M-x</kbd> `customize-group`
`ox-export-twbs`, and emptied the `org-twbs-creator-string`. Restarted Emacs,
and I still see the same.

So I looked into the source code of ox-twbs.

I noticed the following:

```
(defcustom org-twbs-postamble-format
'(("en" "<p class=\"author\">Auteur: %a (%e)</p>
<p class=\"date\">Datum: %d</p>
<p class=\"creator\">%a</p>"))
```

So in my `dot-emacs` I set the following:

```
(setq org-twbs-postamble-format
'(("en" "<p class=\"author\">Auteur: %a (%e)</p>
<p class=\"date\">Datum: %d</p>"))
```

And restarted my Emacs. But that didn't help. I still see the same information
in the footnoter. Could you tell me how I could change the contents of the footnoter?

**Comment by marsmining** [comment]
Hi! You can set `:html-postamble` to one of the values [explained here](http://orgmode.org/manual/HTML-preamble-and-postamble.html#HTML-preamble-and-postamble).

In your case, `t`. For example, at the document level:

``` org
#+TITLE: Simple
#+OPTIONS: html-postamble:t
```

Or at project level via `org-publish-project-alist` variable.

**Comment by ReneFroger** [comment]
That's sweet! Didn't know that the postamble was a feature of the org-mode itself, instead ox-twbs. Now I will figure the org-documentation out in order to change it. Thanks!
