### ISSUE TITLE
link to an absolute filepath still being generated with the current dir prepended

### ISSUE THREAD

**Issue by zhangda82** [marsmining/ox-twbs#20]
Hello,

I enjoyed your ox-twbs add-on a lot, but recently I experienced a technical difficulty: 
When I insert a reference to a file, e.g., [[C:\Users\Da\Documents\work\notes\IT\Mac\somefile.org]], the html file rendered the link as 
file:///C:/Users/Da/Dropbox/GTD/weekly_summary/c:/Users/Da/Documents/work/notes/IT/Mac/somefile.html

I tried to set the following:
      (setq-default org-twbs-link-use-abs-url nil)
But the behavior was not changed. 

Can you shed some light on this issue? 
Thanks!

Da

**Comment by marsmining** [comment]
I don't have a Windows machine to test right now. It looks like a bug though. I'll try to look at it a bit closer tomorrow. In the meantime, why don't you try inputting the `file:` protocol version of the url in the org-mode doc and see if that works as a temporary fix.

**Comment by zhangda82** [comment]
Thanks for the quick response!
I tried file: option, and the problem still exists.

**Comment by marsmining** [comment]
Sorry that didn't help. Generally you are better off using relative links, for example if your org file is in `C:\Users\Da\Documents\work\notes\IT\` and you want to link to an org file in `C:\Users\Da\Documents\work\notes\IT\Mac\` then your link can look like `[[./Mac/somefile.org]]`. Note I used forward slash. I think that is what you would want to do on Windows.

If you really want to use absolute file links in your org docs, try an org document like the following and let me know how it works.

``` org
#+OPTIONS: html-link-use-abs-url:nil

[[file:c:/path/to/filename]]
```

Or try some permutations like `[[/c/path/to/filename]]` or `[[file:/c/path/to/filename]]`.

**Comment by zhangda82** [comment]
Thanks. I tried the local-buffer option, 
#+OPTIONS: html-link-use-abs-url:nil

[[file:c:/path/to/filename]]
and they did not work. 
I tried the cygwin path format, which is similar to the linux/unix path format, and the link was correct. However, the link rendered is not usable under Windows, as the browser does not recognize something like:
/cygdrive/c/Users/Da/Documents/LIT/Breast_Imaging/dose

Any places in your code that I can tweak to solve this problem?
Thanks.

Da

**Comment by marsmining** [comment]
Sorry I haven't been able to help! Relevant [bit of code](https://github.com/marsmining/ox-twbs/blob/fb3bb0dc9c7ded39605fb6dd805b81b25e1c8f19/ox-twbs.el#L2372-L2376).

**Comment by zhangda82** [comment]
I found that the problem was gone after upgrading to the new twbs version. Thanks so much for fixing this!
