### ISSUE TITLE
is there a way to customize the TODO done and undone styles?

### ISSUE THREAD

**Issue by zhangda82** [marsmining/ox-twbs#21]
Hello,

I have some a light customization on the appearance of TODO and TAGS, using org-twbs-head-extra (see the code below). 
However, with the newest version of ox-twbs, this customization stopped working. 
Is there a work-around to make the styles specified in org-twbs-head-extra take higher priority than the default behavior? Thank you very much!

Da

(setq org-twbs-head-extra "<style type=\"text/css\">
/\* @group Org Keywords */

.todo {
    color: #b22222; /_firebrick_/
    background: #fff0f5 /_LavenderBlush_/
}

.done {
    color: #228b22; /_forestgreen_/
    background: #f0fff0 /_honeydew, green-ish_/
}

.tag {
    color: blue;
    background: #e0ffff; /_LightCyan, blue-ish_/
    text-transform: uppercase;
    /\* This will be obscured by the surrounding span tag, so blank everything. */
    border: none;
    text-align: right;
    right: 1em;
}

.timestamp {
}

.timestamp-kwd  {
    /\* keyword associated with a time stamp, like SCHEDULED */
}

.target {
    /\* target for links */
}

/\* @end */
</style>"
            )

**Comment by marsmining** [comment]
You can disable the attempt to style todo keywords and tags with the following:

`#+OPTIONS: toc-todo:nil toc-tag:nil`

Or in your publish configuration with `:with-toc-todo-keywords` and `:with-toc-tags`.

Sorry I've not documented these yet.

**Comment by zhangda82** [comment]
Thanks! Is there a way to hard-code these settings in lisp configuration, or using your function, my-org-publish-buffer, to include these settings?

Da

**Comment by zhangda82** [comment]
Just tried the options, and they seem not working. Thanks.

**Comment by marsmining** [comment]
Sorry, I mis-understood your question. I gave you instructions on todo and tags visibility in table of contents. The proper answer for you is to set the vars `org-twbs-tag-class`, `org-twbs-todo-kwd-class-undone` and `org-twbs-todo-kwd-class-done`. For example:

``` elisp
(setq org-twbs-tag-class "")
(setq org-twbs-todo-kwd-class-undone "")
(setq org-twbs-todo-kwd-class-done "")
```

As for setting things up above the document level, you'd want to setup a [publish project](http://orgmode.org/manual/Publishing.html) config. Hope this helps. Thanks for your feedback!

**Comment by zhangda82** [comment]
Thanks! So by setting these to empty string, tags and todo keywords will not be labeled, correct?
How about if I want to have them labeled, but using other styles (such as the ones I used in the first comment?) Appreciate your help and effort!

Da

**Comment by zhangda82** [comment]
Tried your solution, and it worked!
What I did:

> (setq org-twbs-head-extra "<style type=\"text/css\">
> /\* @group Org Keywords */

.todo {
    color: #b22222; /_firebrick_/
    background: #fff0f5 /_LavenderBlush_/
}

.done {
    color: #228b22; /_forestgreen_/
    background: #f0fff0 /_honeydew, green-ish_/
}

.undone {
    color: #483d8b; /_DarkSlateBlue_/
    background: #efe9ff /\* purple-ish*/
}

.tag {
    color: blue;
    background: #e0ffff; /_LightCyan, blue-ish_/
    text-transform: uppercase;
    /\* This will be obscured by the surrounding span tag, so blank everything. */
    border: none;
    text-align: right;
    right: 1em;
}

.timestamp {
}

.timestamp-kwd  {
    /\* keyword associated with a time stamp, like SCHEDULED */
}

.target {
    /\* target for links */
}

/\* @end */
</style>"
            )
      ;; CF: https://github.com/marsmining/ox-twbs/issues/21#issuecomment-187730234
      (setq org-twbs-tag-class "tag")
      (setq org-twbs-todo-kwd-class-undone "undone")
      (setq org-twbs-todo-kwd-class-done "done")
Looks terrific!

**Comment by marsmining** [comment]
Great! To revert to behavior prior to my recent changes, I think the following would be right:

``` elisp
(setq org-twbs-tag-class "")
(setq org-twbs-todo-kwd-class-undone "todo")
(setq org-twbs-todo-kwd-class-done "done")
```

You can see [the relevant code](https://github.com/marsmining/ox-twbs/blob/38fdd35e483c9fec4a055f60c6bdf6b24e63ae5c/ox-twbs.el#L1534-L1563) to see how they are used.
