### ISSUE TITLE
export breaks when using both toc: t and \n:t in org-options

### ISSUE THREAD

**Issue by zhangda82** [marsmining/ox-twbs#22]
Hello,
I suddenly realized how FANCY your floating table of content is, by accidentally running someone's org file. However, when I used my old org files, I came across an error: 
when I want to enable TOC and \n simultaneously, the exporter report the following error:
org-html-close-tag: Wrong type argument: char-or-string-p, nil

A sample code:
# +OPTIONS: H:1 num:2 toc:t
# +OPTIONS: \n:t

I tried the standard org-html-export, and the export works fine. 
I assume this is an error in the ox-twbs. 

Thanks for the great work!

Da Zhang

**Comment by marsmining** [comment]
Let me know if that fixes your problem. Thanks!

**Comment by zhangda82** [comment]
Yes, after upgrading to 1.08, the problem was solved. 
I saw another strange behavior, though: 
when I have 
#+OPTIONS: H:2 num:1 toc:t
i.e., headline level H: > accepted num:, the TOC was generated, but the links of the non-numbered items on the TOC mess up. For example, try the following code for ox-twbs export. Thanks!
`#+OPTIONS: H:2 num:1 toc:t
#+OPTIONS: \n:t
#+OPTIONS: ^:nil
#+OPTIONS: <:nil todo:t *:t ^:{} ::t |:t TeX:t

# how to change image size: #+ATTR_HTML: :width 40%

# Created: Wed Feb 24 14:10:28 2016

# Update #: 15

# Last-Updated: Mon Mar  7 10:59:57 2016 (-18000 Eastern Standard Time)
- Plan
  *\* 1
  *\* 2
  *\* 3
  *\* 4
- Summary
  *\* Important tasks/projects done this week
  *\* Drawbacks
  *\* Thoughts/Comments
  *\* Time usage
  `
