### ISSUE TITLE
Symbol’s value as variable is void: org-link-escape-chars-browser

### ISSUE THREAD

**Issue by Xparx** [marsmining/ox-twbs#27]
Emacs-version: GNU Emacs 25.1.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-08-11
org-mode-version: Org-mode version 8.3.5 (release_8.3.5-1062-g0fa7f9)

Just tried this package out and this issue came up when trying to export.
I can't find any reference to this variable in my org version.
Currently I just changed it to org-link-escape-char, not sure it's a fix but it seems to not hickup.

**Comment by marsmining** [comment]
Sorry for delay replying! I tried upgrading to org-mode 8.3.5, and did find and fix an issue with LaTeX but didn't encounter this error. Can you paste an org document that triggers the error for you?

**Comment by Xparx** [comment]
Thanks for the reply. I will double check exporting again and post a document if it's not working.

**Comment by Xparx** [comment]
So I still have the same issue. I'm running it on the example org file provided by you. I'm doing an `rgrep` after `org-link-escape-chars-browser` in my org-mode root directory and can't find any references to it. It might be an issue on my end but if possible could you check where this variable is defined in your org directory?
Edit:
To clarify. I can find where this variable is used in ox-twbs but it seems to me like it should already be defined somewhere else.

**Comment by kaushalmodi** [comment]
@Xparx 

This error is because you are using the org version built from its master branch.

The confusion here is because both master and stable branches of org-mode are numbered 8.3.5. But the master branch version is technically 9.x.

**Comment by kaushalmodi** [comment]
@Xparx 

I have a suggested a fix for this in this other issue opened to collect all org 9.x breaking changes: https://github.com/marsmining/ox-twbs/issues/29

**Comment by Xparx** [comment]
Thanks for getting back to this. Had no idea about the version numbering in org. I'll use the suggested branch for now.

**Comment by marsmining** [comment]
Should be compatible with org-9 now.

**Comment by Xparx** [comment]
Awesome!
