### ISSUE TITLE
Table column alignment is not working

### ISSUE THREAD

**Issue by fhaifler** [marsmining/ox-twbs#28]
Exporting columns with specified alignement (etc. `<r>` to align right - as noted [here](https://www.gnu.org/software/emacs/manual/html_node/org/Column-width-and-alignment.html#DOCF28)) does not end with cells aligned to right. 
Resulting html table cells has class `right`, which does not align textual content of the cell to the right. Shouldn't there be class `text-right` instead?

Table example:

``` org
| col1 |
|------|
| <r>  |
| text |
```

Possible fix:
on https://github.com/marsmining/ox-twbs/blob/master/ox-twbs.el#L2893
use `class=\"text-%s\""` instead of just `class=\"%s\""`

**Comment by marsmining** [comment]
Thanks for all the info! I pushed a fix which should show up in Melpa (not stable) within a few hours.

**Comment by marsmining** [comment]
Tagged for melpa-stable just now so should be available in a few hours.

**Comment by fhaifler** [comment]
Awesome! Thanks for the good work.
