### ISSUE TITLE
error casued by the use of export-block

### ISSUE THREAD

**Issue by zhangda82** [marsmining/ox-twbs#32]
Hi!

After the recent org-mode upgrade (20161102), ox-twbs reported the following message: 
(error ("Unknown keyword: :export-block"))

I believe the error is caused by the obsolete keyword ox-block, see http://orgmode.org/Changes.html

Can you please help with the issue? Thanks!

Da

**Comment by zhangda82** [comment]
It seems if you comment out line 109, 
:export-block "HTML"
the problem can be solved. 

Thanks again. 
Da

**Comment by zhangda82** [comment]
Another error after I commented out the :export-block HTML line at line 109 showed up: 
org-export-data: Symbol’s value as variable is void: org-link-escape-chars-browser.

The same message did not show up when using the default html exporter. 

Da

**Comment by zhangda82** [comment]
It seems that "org-link-escape-chars-browser" is also changed to "org-link-escape-chars", in the new org-mode version.

**Comment by marsmining** [comment]
Thanks! Made these changes and pushed…

2414e6b1de7deb6dd2ae79a7be633fdccb9c2f28

**Comment by zhangda82** [comment]
Thanks!
Just another comment/thought: 
The org-mode has been moving forward very quickly without much consideration of the back-compatibility issue of existing external org-mode-addon's. So are there any ways to decouple ox-twbs with emacs-org's ever-changing naming conventions? Or is it possible to make ox-twbs a pure css/js framework? 
Thanks again. 
Da
