### ISSUE TITLE
Junk chacters get generated in the `BEGIN_SRC` block

### ISSUE THREAD

**Issue by mandarvaze** [marsmining/ox-twbs#41]
Junk characters "&#57344;&#57345;&#57345;" get generated in the `BEGIN_SRC` block.
(BTW, these are `&#57344;&#57345;&#57345;` when viewed as HTML source)

Use the following `test.org` and then `M-x org-twbs-export-to-html`

	* Section 1
	** Section 1.1
	#+BEGIN_SRC shell
	$ ipython
	Python 3.5.2 (default, Jan 16 2017, 16:01:21)
	Type "copyright", "credits" or "license" for more information.

	IPython 4.0.1 -- An enhanced Interactive Python.
	?         -> Introduction and overview of IPython's features.
	%quickref -> Quick reference.
	help      -> Python's own help system.
	object?   -> Details about 'object', use 'object??' for extra details.

	In [1]: from datetime import date

	In [2]: date(2017, 6, 27)
	Out[2]: datetime.date(2017, 6, 27)

	In [3]:
	Do you really want to exit ([y]/n)? y
	#+END_SRC

BTW , the exported HTML of this also has some "black boxes" in place of white spaces. This was not seen in my other org file.

**Comment by mandarvaze** [comment]
This seems like some settings that I have not done.

I used `example/eg0.org` and then `org-twbs-export-to-html`
The output I get is not the same as HTML pointed to, in the `README.org`

I also get Section numbers (which I don't want)

So now the question is "what settings" do I need to get beautiful HTML output ?

**Comment by marsmining** [comment]
Thanks for feedback! I'll look closer at this on the weekend… but regarding the section numbers, there is a mention of this in the [readme](https://github.com/marsmining/ox-twbs#general-org-tips).

**Comment by mandarvaze** [comment]
@marsmining Thanks for the tip about section number

Looks like the problem is in org-export, not specific to ox-twbs
I saw similar problem when I created HTML email via mu4e, using `org-mime-htmlize`

Feel free to close, off course it would be nice if you can point me to troubleshooting tips.

**Comment by mandarvaze** [comment]
Looks like this is due to `fill-column-indicator`
See this [reddit](https://www.reddit.com/r/emacs/comments/6ldthb/bug_in_exporting_source_block_from_orgmode_to_html/djtbn3x/) discussion.

The solution is to turn-off `fci-mode` during the htmlize
