### ISSUE TITLE
org has new escape mechanism for links

### ISSUE THREAD

**Issue by ericsfraga** [marsmining/ox-twbs#52]
In the past week or two, the signature for org-link-escape has changed. This causes ox-twbs to break on exporting. Line 2455 of ox-twbs.el needs to be changed to remove the second argument to org-link-escape.

**Comment by abradd** [comment]
The old functions still exist, but were renamed to org-link-encode (previously org-link-escape) and org-link-decode (previously org-link-unescape). So one could either change the function names or remove the second argument. The new implementation of org-link-escape seems simpler as you don't need to provide a table of escaped characters.

This change will only occur in org v9.3 and is documented in ORG-NEWS.

**Comment by marsmining** [comment]
Sorry for delay, and thanks for all the great info!

@ericsfraga how can I try to reproduce? What version of Org are you using? Latest from Melpa seems to be 9.2.3.

**Comment by ericsfraga** [comment]
That version (9.2.3) of org should show up the problem. Any link in a document should cause a problem without the fix.

**Comment by haifenghan** [comment]
Hi marsmining,
If you try the below link with org 9.3, the ox-twbs will encounter the following error:
`org-twbs-link: Wrong number of arguments: (1 . 1), 2`

```
Please see this commit: [[https://github.com/foss-for-synopsys-dwc-arc-processors/synopsys-caffe/commit/86f8b094fec4cc2d2091221cfe3f1b77b5e18a0e][86f8b094fec4cc2d2091221cfe3f1b77b5e18a0e]]
```

**Comment by marsmining** [comment]
Sorry for delay! Should be fixed now!
