### ISSUE TITLE
Export HTML not as source code

### ISSUE THREAD

**Issue by edwinhu** [marsmining/ox-twbs#6]
Is there a way to export HTML not as source code?

For example I would like to do something like:
# +BEGIN_HTML

<ul>
<li> <img src="foo.png" title="foo" />
<li> <img src="bar.png" title="bar" />
</ul>
# +END_HTML

But ox-twbs always exports it in a source code block instead of rendering the HTML as-is. ox-html seems to "correctly" export HTML.

**Comment by marsmining** [comment]
Thanks for feedback! Sorry for delayed reply.

I updated the example in the [readme](https://github.com/marsmining/ox-twbs#example) to include HTML source and inline examples. Take a look and let me know if there is behavior you don't expect.
