### ISSUE TITLE
fixed-width element adds unneccesary newline

### ISSUE THREAD

**Issue by felix11h** [marsmining/ox-twbs#61]
Given Org-mode text

```
Inline code test, some more words, then some code
: hello world
and text again. Shouldn't make two lines, but it does!
```

I do not expect the exported html to add an additional line to the fixed-width `:` block:

> ![output](https://user-images.githubusercontent.com/610633/84405833-f9ddcd00-ac08-11ea-9904-e2bfe6037757.png)

Can anyone confirm this behaviour or is it specific to my settings? 

I believe that the relevant code in `ox-twbs.el` is

``` lisp
(defun org-twbs-fixed-width (fixed-width contents info)
  "Transcode a FIXED-WIDTH element from Org to HTML.
CONTENTS is nil.  INFO is a plist holding contextual information."
  (format "<pre class=\"example\">\n%s</pre>"
          (org-twbs-do-format-code
           (org-remove-indentation
            (org-element-property :value fixed-width)))))
```

I would be happy to prepare a pull-request, but I might need some pointers on how to best tackle the problem. Thank you!

**Comment by marsmining** [comment]
Thanks for reporting! That does seem annoying. I'll take a look this weekend.

**Comment by felix11h** [comment]
Realized that this is still open. Thank you very much for implementing a fix for this. Works like a charm!
