### ISSUE TITLE
"Wrong type argument: sequencep, :input-buffer" error

### ISSUE THREAD

**Issue by thomas-louvigne** [marsmining/ox-twbs#8]
I got this error when i try the export.
It's work on org-html-export-to-html

I am little bit noob and don't know how to debug :-(

**Comment by ghost** [comment]
I got this error too, both on to-html and as-html.

**Comment by marsmining** [comment]
I've pushed changes which should support both org-mode 8.2.x and 8.3.x. Can you try upgrading to recent version and see if things are ok?

Current version is 1.0.0 and on melpa (and stable).

**Comment by ghost** [comment]
It works perfectly now. Thanks!

**Comment by thomas-louvigne** [comment]
it works for me now :dancer:

**Comment by marsmining** [comment]
Thanks for your help! Will close this then.
