### ISSUE TITLE
Printing nil if a heading has CUSTOM_ID but no immediate text

### ISSUE THREAD

**Issue by kaushalmodi** [marsmining/ox-twbs#9]
The below example will explain this problem better than the title:

``` org
# more heading before this, not pasted here
* Blocks
:PROPERTIES:
:CUSTOM_ID: blocks
:END:
*** Normal blocks
: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
: eiusmod tempor incididunt ut labore et dolore magna aliqua.
```

I took the above example from your example org file for twbs export. The only change is that I added the `CUSTOM_ID` property.

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/9583764/307d1828-4fdb-11e5-987e-95a8ba9ac79d.png)

---

If I put some content under that heading **before** the sub-heading, the `nil` string does not get printed.

``` org
# more heading before this, not pasted here
* Blocks
:PROPERTIES:
:CUSTOM_ID: blocks
:END:
some content
*** Normal blocks
: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
: eiusmod tempor incididunt ut labore et dolore magna aliqua.
```

**Comment by marsmining** [comment]
Thanks for feedback! I've committed a fix, melpa should update within a couple hours.
